[package]
name = "semver-example"
version = "0.1.0"
edition = "2021"

[dependencies]

semver = "1.0"


[dev-dependencies]
cargo-semver-checks = "0.22"

[lib]
name = "semver_example"
path = "src/lib.rs"